export const SUCCESS_REMOVE_ITEM_FROM_CART = 'SUCCESS_REMOVE_ITEM_FROM_CART';
export const FAILURE_REMOVE_ITEM_FROM_CART = 'FAILURE_REMOVE_ITEM_FROM_CART';

export const SUCCESS_CLEAR_CART = 'SUCCESS_CLEAR_CART';
export const FAILURE_CLEAR_CART = 'FAILURE_CLEAR_CART';

export const SUCCESS_GET_CART_ITEMS = 'SUCCESS_GET_CART_ITEMS';
export const FAILURE_GET_CART_ITEMS = 'FAILURE_GET_CART_ITEMS';

export const COUNT_NUMBER_OF_ITEMS_IN_CART = 'COUNT_NUMBER_OF_ITEMS_IN_CART';
