export const SUCCESS_GET_PROFILE_INFO = 'SUCCESS_GET_PROFILE_INFO';
export const FAILURE_GET_PROFILE_INFO = 'FAILURE_GET_PROFILE_INFO';

export const SUCCESS_GET_ORDERS = 'SUCCESS_GET_ORDERS';
export const FAILURE_GET_ORDERS = 'FAILURE_GET_ORDERS';

export const SUCCESS_CREATE_ORDER = 'SUCCESS_CREATE_ORDER';
export const FAILURE_CREATE_ORDER = 'FAILURE_CREATE_ORDER';
