//NEXT
export const SET_REGISTER_NEXT_PAGE = 'SET_REGISTER_NEXT_PAGE';
export const SET_REGISTER_PREVIOUS_PAGE = 'SET_REGISTER_PREVIOUS_PAGE';

// INPUT
export const INPUT_REGISTER_FULL_NAME = 'INPUT_REGISTER_FULL_NAME';
export const INPUT_REGISTER_EMAIL = 'INPUT_REGISTER_EMAIL';
export const INPUT_REGISTER_PASSWORD = 'INPUT_REGISTER_PASSWORD';
export const INPUT_REGISTER_REPEAT_PASSWORD = 'INPUT_REGISTER_REPEAT_PASSWORD';
export const INPUT_REGISTER_ADDRESS = 'INPUT_REGISTER_ADDRESS';
export const INPUT_REGISTER_CARD = 'INPUT_REGISTER_CARD';
export const INPUT_REGISTER_PHONE = 'INPUT_REGISTER_PHONE';

// REQUEST
export const SUCCESS_REQUEST_REGISTER = 'SUCCESS_REQUEST_REGISTER';
export const FAILURE_REQUEST_REGISTER = 'FAILURE_REQUEST_REGISTER';
