export const INPUT_LOGIN_EMAIL = 'INPUT_LOGIN_EMAIL';
export const INPUT_LOGIN_PASSWORD = 'INPUT_LOGIN_PASSWORD';

export const SUCCESS_LOGIN_REQUEST = 'SUCCESS_LOGIN_REQUEST';
export const FAILURE_LOGIN_REQUEST = 'FAILURE_LOGIN_REQUEST';
